

# data
# TRAINING_DATA_FILE = "data/ETF_SPY_2009_2020.csv"
TRAINING_DATA_FILE = "data/dow_30_2009_2020.csv"

ALL_STOCKS_DATA_FILE="data/all_stocks.csv"


TRAINED_MODEL_DIR = "trained_models"
TURBULENCE_DATA = "data/dow30_turbulence_index.csv"

TESTING_DATA_FILE = "test.csv"


indexes = [
    "^GSPC",
    "^TNX",
    "DJI",
    "^IXIC",
    "UKX",
    "VTI",
    "VT",
    "^RUT",
    "^BUK100P",
    "^FTSE",
    "^N100",
    "CBOE",
    "^VIX",
    "FNILX",
    "IVV",
    "SWPPX",
    "VOO",
]

tech_tickers = [
    "ADBE",
    "BA",
    "CSCO",
    "DIS",
    "INTC",
    "V",
    "FB",
    "GOOGL",
    "AMZN",
    "MSFT",
    "AAPL",
    "TSLA",
    "PYPL",
    "NVDA",
    "CRM",
    "NFLX",
    "BABA",
    "AMD"
]

cyclical = [
    'BA','AMZN','AAPL','DIS','INTC','WMT','AUDVF','F','VWAGY','PCRFY',
]

ticker_list = [
    "ADBE",
    "BA",
    "WFC",
    "PEP",
    "CMCSA",
    "CSCO",
    "CVX",
    "PFE",
    "MRK",
    "VZ",
    "KO",
    "DIS",
    "HD",
    "XOM",
    "UNH",
    "T",
    "INTC",
    "BAC",
    "PG",
    "MA",
    "WMT",
    "JNJ",
    "JPM",
    "V",
    "FB",
    "GOOGL",
    "AMZN",
    "MSFT",
    "AAPL",
    "TSLA",
    "PYPL",
    "NVDA",
    "CRM",
    "HON",
    "NFLX",
    "LLY",
    "NKE",
    "TMO",
    "AVGO",
    "ABBV",
    "AXP",
    "AMCR",
    "BLK",
    "SCHW",
    "C",
    "ROK",
    "TSN",
    "HFC",
]

ticker_list_with_dict = [
    "ADBE",
    "BA",
    "WFC",
    "PEP",
    "CMCSA",
    "CSCO",
    "CVX",
    "PFE",
    "MRK",
    "VZ",
    "KO",
    "DIS",
    "HD",
    "XOM",
    "UNH",
    "T",
    "INTC",
    "BAC",
    "PG",
    "MA",
    "WMT",
    "JNJ",
    "JPM",
    "V",
    "GOOGL",
    "AMZN",
    "MSFT",
    "AAPL",
    {"out_stock": "COP", "in_stock": "TSLA", "swap_date": "2017-10-10"},
    {"out_stock": "TSN", "in_stock": "FB", "swap_date": "2016-10-10"},
    {"out_stock": "ROK", "in_stock": "ABBV", "swap_date": "2013-10-10"},
    {"out_stock": "HFC", "in_stock": "PYPL", "swap_date": "2013-10-10"},
    "NVDA",
    "CRM",
    "HON",
    "NFLX",
    "LLY",
    "NKE",
    "TMO",
    "AVGO",
    "AXP",
    "EFX",
    "BLK",
    "SCHW",
    "C",
]

category_dict = {
    "ADBE": "Software",
    "BA": "Technology",
    "WFC": "Banks and Financials",
    "PEP": "Soft Drinks",
    "CMCSA": "Telecommunications",
    "CSCO": "Technology",
    "CVX": "Petroleum",
    "PFE": "Pharmaceutical",
    "MRK": "Pharmaceutical",
    "VZ": "Telecomunication",
    "KO": "Soft Drinks",
    "DIS": "Entertainment",
    "KO": "Retail",
    "HD": "Retail",
    "XOM": "Petroleum",
    "UNH": "Pharmaceutical",
    "T": "Telecommunications",
    "INTC": "Technology",
    "BAC": "Banks and Financials",
    "PG": "Consumer Good",
    "MA": "Banks and Financials",
    "WMT": "Retail",
    "JNJ": "Pharmaceutical",
    "JPM": "Banks and Financials",
    "V": "Banks and Financials",
    "BRK": "Banks and Financials",
    "FB": "Software",
    "GOOGL": "Software",
    "AMZN": "Software",
    "AAPL": "Technology",
    "MSFT": "Technology",
    "TSLA": "EV",
    "PYPL": "Software",
    "NVDA": "Technology",
    "CRM": "Software",
    "NFLX": "Software",
    "LLY": "Pharmaceutical",
    "NKE": "Consumer Good",
    "TMO": "Pharmaceutical",
    "HON": "Technology",
    "AVGO": "Telecommunications",
    "ABBV": "Pharmaceutical",
    "AXP": "Banks and Financials",
    "AMCR": "Materials",
    "BLK": "Banks and Financials",
    "SCHW": "Banks and Financials",
    "C": "Banks and Financials",
    "COP": "Gas",
    "TSN": "Food",
    "ROK": "Robotics",
    "EFX": "Banks and Financials",
    "HFC": "Petroleum",
}
